'use strict';
const R=window.GameRules,$=id=>document.getElementById(id);
let state=R.initialState(),stage='search',demoIntroMode=false;
function enter(target){state=R.initialState();if(['nav','reco','service'].includes(target))state.search.done=true;if(['reco','service'].includes(target))state.nav.done=true;if(target==='service')state.reco.done=true;stage=target;demoIntroMode=target.startsWith('hall:');render();}
function act(action){const out=R.step(state,action);state=out.state;render();}
function render(){
 const s=state[stage];$('demo-stage').value=stage;$('demo-message').textContent=stage.startsWith('hall:')?`${window.GalleryModel.halls.find(h=>h.id===stage.slice(5)).name} · ${demoIntroMode?'先看应用介绍，再体验演示':'改变输入条件，观察结果'} · 本页不写入学生记录`:`${state.last.text} · 当前虚构完成：${Object.keys(R.points).filter(id=>state[id].done).join('、')||'尚无'}`;
 if(stage==='search')$('demo-content').innerHTML=`<h2>找活动 · 第${Math.min(s.guest+1,2)}位游客</h2><p>${R.searchGuests[Math.min(s.guest,1)].wish}</p><div class="demo-grid"><div class="demo-card"><h3>搜索线索</h3><button class="secondary-button" data-kind="search" data-val="植物,识别">植物＋识别</button><button class="secondary-button" data-kind="search" data-val="植物,手工">植物＋手工</button><button class="secondary-button" data-kind="search" data-val="拍照">拍照</button></div><div class="demo-card"><h3>发活动邀请</h3>${R.activities.map(a=>`<button class="secondary-button" data-kind="invite" data-val="${a.id}">${a.id} ${a.title}</button>`).join('')}</div><div class="demo-card"><h3>说明依据</h3><button class="secondary-button" data-kind="reason">匹配游客的需要并核对活动内容</button></div></div>`;
 if(stage==='nav'&&s.phase<4)$('demo-content').innerHTML=`<h2>带游客 · 第${s.phase+1}位</h2><p>${R.navMissions[s.phase].text}</p><div class="demo-grid">${R.routeChoices(s.phase).map(r=>`<div class="demo-card"><h3>${r.id} ${r.name}</h3><p>${r.meters}米 · ${r.minutes}分钟 · ${r.open?'可通行':'封闭'}</p><button class="secondary-button" data-kind="route" data-val="${r.id}">带游客出发</button></div>`).join('')}</div>`;
 if(stage==='nav'&&s.phase>=4)$('demo-content').innerHTML='<h2>带路原因</h2><button class="secondary-button" data-kind="nav-reason">道路通行和预计用时改变，要按游客目标重选</button>';
 if(stage==='reco'&&s.phase<4){$('demo-content').innerHTML=`<h2>推荐 · 第${s.phase+1}位</h2><p>${R.recommendation(s.phase).wish}</p><p>过去记录：${Object.entries(R.recommendation(s.phase).history).map(([id,n])=>`${id} ${n}次`).join(' · ')}</p><div class="demo-grid">${['S','T','U'].map(id=>`<div class="demo-card"><h3>${id}</h3><button class="secondary-button" data-kind="predict" data-val="${id}">先预测${id}</button><button class="secondary-button" data-kind="reco" data-val="${id}">发${id}邀请</button></div>`).join('')}</div>`;}
 if(stage==='reco'&&s.phase>=4)$('demo-content').innerHTML='<h2>推荐原因</h2><button class="secondary-button" data-kind="reco-reason">历史记录提供建议，当前需要仍要由人判断</button>';
 if(stage==='service')$('demo-content').innerHTML=`<h2>服务卡</h2><div class="demo-grid">${Object.entries(R.topics).map(([id,t])=>`<div class="demo-card"><h3>${t.label}</h3><p>${t.input} → ${t.action} → ${t.benefit}</p><button class="secondary-button" data-kind="service" data-val="${id}">提交这张服务卡</button></div>`).join('')}</div>`;
 if(stage.startsWith('hall:')){const id=stage.slice(5),records=state.gallery.records[id]||[];$('demo-content').innerHTML=(demoIntroMode?window.GalleryUI.renderIntro(id):window.GalleryUI.renderHall(id,records)).replace('<button class="text-button" type="button" data-hall="hub">← 返回体验馆一览</button>','<span>切换体验馆请用上方选择</span>');if(!demoIntroMode)window.GalleryUI.afterRender(id,records.at(-1));}
}
$('demo-stage').addEventListener('change',e=>enter(e.target.value));$('demo-reset').addEventListener('click',()=>enter(stage));
$('demo-answers').addEventListener('click',()=>{$('demo-answer-box').hidden=false;$('demo-answer-content').innerHTML='<p>找活动：小芽选择A叶子侦探，阿木选择B叶子拓印；要核对海报内容。带游客：初始最快B、最短A；中心路封闭后最快C；中心路变为7分钟后最快仍为C。推荐：S、U、U；最后一位游客虽然历史推荐T，但当前明确要科学探索，应发S。服务卡按同一主题对应信息、处理与帮助，开放补充由教师判断。</p>';});
$('demo-content').addEventListener('click',e=>{const intro=e.target.closest('[data-action]');if(intro?.dataset.action==='gallery-enter'||intro?.dataset.action==='gallery-intro'){demoIntroMode=intro.dataset.action==='gallery-intro';render();return;}const b=e.target.closest('[data-kind]');if(!b)return;const id=b.dataset.val;switch(b.dataset.kind){case'search':act({type:'search/query',terms:id.split(',')});break;case'invite':act({type:'search/invite',id});break;case'reason':act({type:'search/reason',reason:'匹配游客的需要并核对活动内容'});break;case'route':act({type:'nav/choose',route:id});break;case'nav-reason':act({type:'nav/reason',reason:'道路通行和预计用时改变，要按游客目标重选'});break;case'predict':act({type:'reco/predict',id});break;case'reco':act({type:'reco/invite',id});break;case'reco-reason':act({type:'reco/reason',reason:'历史记录提供建议，当前需要仍要由人判断'});break;case'service':act({type:'service/submit',topic:id,...R.topics[id]});break;}});
$('demo-content').addEventListener('submit',event=>{if(event.target.id==='gallery-form'){event.preventDefault();const hall=event.target.dataset.hallId;act({type:'gallery/run',hall,input:window.GalleryUI.readInput(hall)});}});
$('demo-content').addEventListener('input',event=>{if(event.target.classList.contains('gallery-range')){const out=document.getElementById(event.target.dataset.output);if(out)out.value=event.target.value;}});
render();
